### ISSUE TITLE
Classic Card Viewer broken

### ISSUE THREAD

**Issue by seanccsmith** [ftrotter/LoreCommander#6]
The Classic Card Viewer search page under Card Layout Reports returns an error when visited (screenshot). Could this be due to a changed table schema somewhere? 
![Screen Shot 2020-05-06 at 9 51 54 AM](https://user-images.githubusercontent.com/42678849/81222563-13587d00-8faa-11ea-9ef0-467aa4ede6e9.png)

I believe this is a separate issue from that affecting the Card Search Using Card Display and Card Search Using Grid Display.

**Comment by kchapple** [comment]
This was fixed in zermelo, see zermelo issues #122 and #123
